---

- debug: var=gpg_key_gen_files

## expect method (installs lots of stuff)

- name: "ensure that expect is installed"
  become: true
  apt:
    name: 'expect'
    state: present
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'

- debug: var=gpg_key_user

- name: "copy over gpg.conf file"
  become: '{{ gpg_key_user }}'
  copy:
    src : 'files/gpg.conf'
    dest: '~/{{ gpg_key_basedir }}/gpg.conf'
    owner: "{{ gpg_key_user }}"
    group: "{{ gpg_key_user }}"
    mode: 0600
  when: gpg_keys.stdout == ""

- name: "copy over set-trust-ultimate.exp script"
  become: '{{ gpg_key_user }}'
  copy:
    src : 'files/set-trust-ultimate.exp'
    dest: '~/{{ gpg_key_basedir }}/set-trust-ultimate.exp'
    owner: "{{ gpg_key_user }}"
    group: "{{ gpg_key_user }}"
    mode: 0700
  when: gpg_keys.stdout == ""

- name: "shell > gpg2 --list-keys | grep pub | grep -o -P '(?<=/)[A-Z0-9]{8}'"
  shell: gpg2 --list-keys | grep pub | grep -o -P '(?<=/)[A-Z0-9]{8}'
  become: '{{ gpg_key_user }}'
  register: gpg_key_id

- debug: var=gpg_key_id.stdout
- debug: var=gpg_key_user
- debug: var=gpg_key_basedir
- debug: var=gpg_key_id.stdout

- name: "template set-trust.sh"
  become: '{{ gpg_key_user }}'
  template:
    src  : 'set-trust.sh.j2'
    dest : '~/{{ gpg_key_basedir }}/set-trust.sh'
    owner: '{{ gpg_key_user }}'
    group: '{{ gpg_key_user }}'
    mode: '0755'

- name: "Execute ~/{{ gpg_key_basedir }}/set-trust.sh"
  become: '{{ gpg_key_user }}'
  shell: ~/{{ gpg_key_basedir }}/set-trust.sh
  when: gpg_keys.stdout == ""
  register: set-trust.sh_output

- debug: var=set-trust.sh_output

#- name: "execute set-trust-exp - ~/{{ gpg_key_basedir }}/set-trust-ultimate.exp {{ gpg_key_id.stdout }}"
#  become: '{{ gpg_key_user }}'
#  shell: '~/{{ gpg_key_basedir }}/set-trust-ultimate.exp {{ gpg_key_id.stdout }}'
#  command: '~/{{ gpg_key_basedir }}/set-trust-ultimate.exp {{ gpg_key_id.stdout }}'
#  command: './set-trust-ultimate.exp {{ gpg_key_id.stdout }}'
#  args:
#    chdir: "~/{{ gpg_key_basedir }}"
#  when: gpg_keys.stdout == ""
#  register: set-trust-ultimate_output

#- debug: var=set-trust-ultimate_output

#- name: "get gpg id"
#  become: '{{ gpg_key_user }}'
#  shell: gpg2 --list-keys | grep pub | grep -o -P '(?<=/)[A-Z0-9]{8}'
#  register: pass_gpg_key_id
#  when: ansible_os_family == 'Debian'

#- name: "get gpg id"
#  become: '{{ gpg_key_user }}'
#  shell: echo "$( \
#           gpg2 --list-keys --fingerprint \
#           | grep `gpg2 --list-keys | grep pub | grep -o -P '(?<=/)[A-Z0-9]{8}'` -A 1 | tail -1 \
#           | tr -d '[:space:]' | awk 'BEGIN { FS = "=" } ; { print $2 }' \
#         ):6:" | gpg2 --import-ownertrust;
#  when: gpg_keys.stdout == ""


